# This pipeline will:
# - Provision an Azure VM.
# 
# 
#
# The following variables need to be provided to the pipeline:
#
# - subscriptionId           : Subscription Id.
# - resourceGroupName        : The name for the Resource Group where vm will be created.
# - snapshotNameOs           : Name for snapshot containing the OS.

#
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'MyAzureServiceConnection'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  subscriptionId: "0ac447d7-fbc3-4d3d-84d4-37bb9a71e089"


stages:

- stage: Convert_block_blobs_to_page_blobs
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'MyAzureServiceConnection'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          azcopy copy "$(source_blob_OsDisk_1_snap)" "$(destination_blob_OsDisk_1_snap)" --blob-type PageBlob
          azcopy copy "$(source_blob_DataDisk_1_snap)" "$(destination_blob_DataDisk_1_snap)" --blob-type PageBlob